[25] Add bell sound packs (ZTM Transit bell / more)
debatecore/debate-tools pull request #49
Opened 2024-05-27 06:55 UTC by Mateusz-Dobrzynski

Implements #25. This PR implements support for ZTM Poznań pack. Other sound packs can be added by expanding `types/soundPack.ts`. Submitting custom sound packs to be done later.

2024-05-27 11:01 UTC, jakubmanczak requested changes

2024-05-27 11:01 UTC, jakubmanczak commented on src/app/oxford-debate/page.tsx
> +          <Dots stages={[0, 2, 4, 6]} stage={stage} flashCurrent={running && !advocem} />
This is aimless, probably due to a code formatter, right? I feel like the prior version was more readable.

2024-05-27 11:01 UTC, jakubmanczak commented on src/app/oxford-debate/page.tsx
> +const Dots = (props: { stages: number[]; flashCurrent: boolean; stage: number }) => {
This makes things more difficult to read - too many things going on.

2024-05-28 07:10 UTC, Mateusz-Dobrzynski commented
Fixed. We probably should unify configs of our code formatters to avoid such hiccups in the future.

2024-05-28 11:48 UTC, jakubmanczak commented
I think adding a preview of these new sounds to the Sound Demonstration page would be nice, as well as a file in the public directory about their origin, to supplement our license.

Something like

"LICENSE-NOTE"
```
The following files in this directory are sourced from ...
under the following terms ...
and are not subject to the distribution terms in the general LICENSE file...
Whatever else... Blah blah ... Don't sue us
```

2024-05-28 11:50 UTC, jakubmanczak commented
There's also still a lot of these aimless changes which you can observe in the 'Files Changed' diff that mess up the git blame.

2024-05-28 12:24 UTC, Mateusz-Dobrzynski commented
I think a `LICENSE-NOTE`, is an awkward solution (especially that the name is not quite descriptive). ZTM sounds are not our only dependencies. It's the only one that requires attribution (for now) but I think could devise a future-proof solution, should we add more attribution-required dependencies. On a related note, the motions from the Generator could use an attribution, too.

2024-05-29 18:57 UTC, jakubmanczak approved these changes

2024-05-29 19:34 UTC, merged